#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License, v2 or later

RFL_PLUGINS="ssd"
. /usr/share/openrc-rfl/main || exit 1

command="/usr/bin/deluged"
command_args="--do-not-daemonize ${deluged_args}"
command_background="true"
procname="deluged"
pidfile="/run/${RC_SVCNAME}.pid"

: ${wait:=2000}
: ${retry:="TERM/5/TERM/5/TERM/2/KILL"}

rfl_ssd_args

depend() {
    need net
}

start_pre() {
    rfl_require_var user
}
